### PR TITLE
Improved exact solvers

### PR DESCRIPTION
**Pull request by lquenti**
Implement the single threaded version of all (prune based) exact solvers

### CODE REVIEW

**Comment by lquenti** [comment]
@johann-cm would you mind merging your code? In the Cargo.toml just include all packages, we both use the same crate version.

In the src/mst.rs, you are better equipped with merging it.

**Comment by johann-cm** [comment]
> would you mind merging your code

what code should I merge whereto?

**Comment by johann-cm** [comment]
There seems to be a lot of code duplication in `solvers/exact.rs`.
Is it possible to implement some smaller functions that can be re-used in all of your solvers?

**Comment by lquenti** [comment]
> > would you mind merging your code
> 
> what code should I merge whereto?

The mst.rs

**Comment by lquenti** [comment]
> There seems to be a lot of code duplication in `solvers/exact.rs`. Is it possible to implement some smaller functions that can be re-used in all of your solvers?

I kind of give up for now and would say that, at least for the time being, we leave it this way.

The best idea I had was to use a `lower_bound` higher order function that can get passed into the recursive function.

After some iteration, I came to the following result:
```rust
fn _improved_solver_rec<'a, T, F>(
    graph_matrix: &'a T,
    current_prefix: &'a mut Path,
    current_cost: f64,
    result: &mut Solution,
    lower_bound: F
) where
    T: AdjacencyMatrix,
    F: Fn(f64, &'a T, &'a Path, usize) -> f64 + Clone
{
    let n = graph_matrix.dim();
    let mut current_cost = current_cost;

    // Base case: Is this one better?
    if current_prefix.len() == n {
        // Add the last edge, finishing the circle
        current_cost += graph_matrix.get(
            *current_prefix.last().unwrap(),
            *current_prefix.first().unwrap(),
        );

        let best_cost = result.0;
        if current_cost < best_cost {
            result.0 = current_cost;
            result.1 = current_prefix.clone();
        }
        return;
    }

    // Branch down with branching factor n-k, where k is the length of current_prefix
    for i in 0..n {
        // We do not visit twice
        if current_prefix.contains(&i) {
            continue;
        }

        current_prefix.push(i);
        // If this is a single element, we do not have an edge yet
        if current_prefix.len() == 1 {
            _improved_solver_rec(graph_matrix, current_prefix, current_cost, result, lower_bound.clone());
            current_prefix.pop();
            continue;
        }

        // Calculate the cost of our new edge
        let from = current_prefix.len() - 2;
        let to = from + 1;
        let cost_last_edge = graph_matrix.get(current_prefix[from], current_prefix[to]);
        current_cost += cost_last_edge;

        let lb = lower_bound(
            current_cost,
            graph_matrix,
            current_prefix,
            n
        );
        if lb <= result.0 {
            _improved_solver_rec(graph_matrix, current_prefix, current_cost, result, lower_bound.clone());
        }

        // Remove the last edge
        current_cost -= cost_last_edge;
        current_prefix.pop();
    }
}
```
Due to those explicit lifetimes, the borrow checker cries everytime we re-borrow `current_prefix`, which is like every second line. I have no idea how to fix this without copying...

**Comment by lquenti** [comment]
I'd suggest that we make a new issue out of it. I can also write it if you are okay with that

**Comment by johann-cm** [comment]
Lgtm

**Pull request merged**
